# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: build
  jobs:
  - job: 'BuildAndPush'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
        checkStyleRunAnalysis: true

    - task: CopyFiles@2
      inputs:
        Contents: 'target/*.jar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        flattenFolders: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: deploy_dev
  jobs:
  - deployment: 'DeployToDev'
    pool:
      vmImage: 'ubuntu-latest'
    environment: Devlopment
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy Stage App Service'
            inputs:
              azureSubscription: '$(Parameters.ConnectedServiceName)'
              appType: 'webAppLinux'
              WebAppName: 'SVCICDDemoApp'
              packageForLinux: '$(Build.ArtifactStagingDirectory)/drop/app.jar'
              RuntimeStack: 'JAVA|8-jre8'
- stage: deploy_stage
  jobs:
  - deployment: 'DeployToDev'
    pool:
      vmImage: 'ubuntu-latest'
    environment: Stage
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy Stage App Service'
            inputs:
              azureSubscription: '$(Parameters.ConnectedServiceName)'
              appType: 'webAppLinux'
              WebAppName: 'SVCICDDemoApp'
              packageForLinux: '$(Build.ArtifactStagingDirectory)/drop/app.jar'
              RuntimeStack: 'JAVA|8-jre8'

